version: '3.7'
services:
  postgresql:
    container_name: parking-map-backend-postgresql
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
  keycloak:
    container_name: parking-map-backend-keycloak
    image: docker.io/bitnami/keycloak:latest
    env_file:
      - .env
    ports:
      - "${KEYCLOAK_PORT}:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=${DB_NAME}
      - KEYCLOAK_DATABASE_USER=${DB_USERNAME}
      - KEYCLOAK_DATABASE_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - postgresql